steps:
- name: 'abdennour/eksctl:0.24.0-aws-1.18.105-kubectl-v1.18.6'
  entrypoint: 'bash'
  args: ['run.sh']
  secretEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']
timeout: 1800s
secrets:
- kmsKeyName: projects/hrznfactory/locations/global/keyRings/keyring/cryptoKeys/key
  secretEnv:
    AWS_ACCESS_KEY_ID: CiQA/t63gSa6fFaQ5kKJ8D1iypGnLfNap62P+NP/4p5XhiYWIgcSPQA2yBtTCRD4trIrR+80sj9dDOtO014KsgtcvNysOoXKn6RAjkzsfMUS4Er2T/luPDX83+SdwSm/MyRotQI=
    AWS_SECRET_ACCESS_KEY: CiQA/t63gRtDjRyOQ/PahwsaqmVY7UyPOptHMCn46gHMFC6lguMSUQA2yBtTJD7hLAu1jIsvngHL6buKVIffi3mUGNg+7bAF3/NxSzo6UkAp+eqjg6P9TKObkjt7P/30niRBgsDA0CPw9utHHnHd+kSDrZrRunY8oQ==
